### PR TITLE
Updated description and load the appropriate libraries

### PR DESCRIPTION
**Pull request by csese**

### CODE REVIEW

**Comment by jbkunst** [comment]
Hi! Thank you so much. I'll put you as collaborator, is it ok for you?

**Comment by jbkunst** [comment]
Hi! Thank you so much. Any name to put you as collaborator?

**Comment by csese** [comment]
Hi, 

I am Charles Sese.

Thank you for the package. 
I noticed that when combined to another htmlwidget such as networkd3,  the word cloud does not work on the shiny app. 
I am no sure why. I will make a reproducible example tomorrow to try to find the problem.  

Thanks,
Charles Sese

**Comment by csese** [comment]
Hi, 

As you can see in this example, the worcloud tab is not working. 

When you comment the output for the network graph, the worcloud appears. 

Do you have any idea on the reason why it happens? 

Thanks,

Charles

**Comment by jbkunst** [comment]
Ok, I'll check to know what is going on.

Thanks,

Joshua

**Pull request merged**
